# Utiliser l'image officielle de MariaDB
FROM mariadb:10.5

# Copiez votre fichier SQL d'initialisation dans le conteneur
COPY ./BD.sql /docker-entrypoint-initdb.d/

# Optionnel : si vous souhaitez ajouter d'autres étapes de personnalisation

